version: '3.7'
networks:
  internal:
    external: false
services:
  ccujuicewebscrape:
    container_name: ccujuicewebscrape
    build:
      context: "./"
      dockerfile: "Dockerfile"
    environment:
      - POSTGRES_USER=ccujuice
      - POSTGRES_PASSWORD=ccujuice
      - POSTGRES_DB=ccujuice
    depends_on:
      - postgresdb    # restart: always
    networks:
      - internal
  postgresdb:
    container_name: postgresdb
    image: postgres:alpine
    environment:
      - POSTGRES_USER=ccujuice
      - POSTGRES_PASSWORD=ccujuice
      - POSTGRES_DB=ccujuice
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal
volumes:
  db_data:
